# Project
version=1.2.2
group=com.evandev.reliable_backpacks
java_version=17

# Common
minecraft_version=1.19.2
mod_name=Reliable Backpacks
mod_author=Spydnel, Evan
mod_id=reliable_backpacks
license=MIT
credits=
description=A backpack mod focusing on balance and simplicity!
minecraft_version_range=[1.19, 1.19.2)

# Parchment
parchment_minecraft=1.19.2
parchment_version=2022.11.27

# Dependencies
cloth_config_version=8.3.134
mod_menu_version=4.1.2
emi_version=1.1.22+1.19.2
mixinextras_version=0.3.5
iris_version=1.6.11+1.19.2
oculus_version=1.19.2-1.6.9a
spyglass_improvements_version=1.5.12+mc1.19
figura_version_fabric=gFlLgoV5
figura_version_forge=Th6hJi2q
curios_version=1.19.2-5.1.6.4
trinkets_version=3.4.1

# Fabric
fabric_version=0.77.0+1.19.2
fabric_loader_version=0.16.9

# Forge
forge_version=43.4.12
forge_loader_version_range=[41,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false